package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	authtransport "github.com/sidsharma96/SysEscape/internal/auth/transport"
	catalogrepo "github.com/sidsharma96/SysEscape/internal/catalog/repo"
	"github.com/sidsharma96/SysEscape/internal/graphql/generated"
	"github.com/sidsharma96/SysEscape/pkg/models"
)

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*generated.Viewer, error) {
	user, ok := authtransport.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}

	var githubUsername *string
	if user.GitHubUsername != "" {
		u := user.GitHubUsername
		githubUsername = &u
	}

	return &generated.Viewer{
		UserID:         user.ID.String(),
		Role:           user.Role,
		GithubUsername: githubUsername,
	}, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, engine *generated.RoomEngine, difficulty *generated.RoomDifficulty, district *string) ([]*generated.Room, error) {
	if r.CatalogRepo == nil {
		return nil, fmt.Errorf("catalog repo is nil")
	}

	filter := catalogrepo.RoomFilter{
		District: district,
	}

	if engine != nil {
		e := string(*engine)
		filter.Engine = &e
	}
	if difficulty != nil {
		d := string(*difficulty)
		filter.Difficulty = &d
	}

	rooms, err := r.CatalogRepo.List(ctx, filter)
	if err != nil {
		return nil, err
	}

	result := make([]*generated.Room, 0, len(rooms))
	for _, room := range rooms {
		result = append(result, mapRoom(room))
	}
	return result, nil
}

// RoomBySlug is the resolver for the roomBySlug field.
func (r *queryResolver) RoomBySlug(ctx context.Context, slug string) (*generated.Room, error) {
	if r.CatalogRepo == nil {
		return nil, fmt.Errorf("catalog repo is nil")
	}

	room, err := r.CatalogRepo.GetBySlug(ctx, slug)
	if err != nil {
		return nil, err
	}
	if room == nil {
		return nil, nil
	}
	return mapRoom(*room), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

func mapRoom(room models.RoomWithLatestVersion) *generated.Room {
	var latestVersion *generated.RoomVersion
	if room.LatestVersion != nil {
		latestVersion = &generated.RoomVersion{
			ID:            room.LatestVersion.ID.String(),
			VersionNumber: room.LatestVersion.VersionNumber,
			Status:        generated.RoomVersionStatus(room.LatestVersion.Status),
			Changelog:     room.LatestVersion.Changelog,
			PublishedAt:   room.LatestVersion.PublishedAt.UTC().Format(time.RFC3339),
		}
	}

	return &generated.Room{
		ID:            room.ID.String(),
		Slug:          room.Slug,
		Title:         room.Title,
		District:      room.District,
		Engine:        generated.RoomEngine(room.Engine),
		Difficulty:    generated.RoomDifficulty(room.Difficulty),
		Description:   room.Description,
		LatestVersion: latestVersion,
	}
}
