package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"

	authtransport "github.com/sidsharma96/SysEscape/internal/auth/transport"
	catalogrepo "github.com/sidsharma96/SysEscape/internal/catalog/repo"
	engineasvc "github.com/sidsharma96/SysEscape/internal/engine/a/service"
	"github.com/sidsharma96/SysEscape/internal/graphql/generated"
	publishsvc "github.com/sidsharma96/SysEscape/internal/platform/publish"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// PublishRoomVersion is the resolver for the publishRoomVersion field.
func (r *mutationResolver) PublishRoomVersion(ctx context.Context, input generated.PublishRoomVersionInput) (*generated.PublishRoomVersionPayload, error) {
	user, ok := authtransport.UserFromContext(ctx)
	if !ok || user.Role != "ADMIN" {
		return nil, &gqlerror.Error{
			Message: "forbidden",
			Extensions: map[string]any{
				"code": "FORBIDDEN",
			},
		}
	}
	if r.PublishService == nil {
		return nil, fmt.Errorf("publish service is nil")
	}

	roomVersion, err := r.PublishService.Publish(ctx, publishsvc.PublishInput{
		ClientRequestID:  input.ClientRequestID,
		UserID:           user.ID,
		RoomSlug:         input.RoomSlug,
		Version:          input.Version,
		Changelog:        input.Changelog,
		BundleHashSha256: input.BundleHashSha256,
		Activate:         input.Activate,
	})
	if err != nil {
		switch {
		case errors.Is(err, publishsvc.ErrIdempotencyConflict):
			return nil, &gqlerror.Error{
				Message: "idempotency conflict",
				Extensions: map[string]any{
					"code": "CONFLICT",
				},
			}
		case errors.Is(err, publishsvc.ErrRequestInProgress):
			return nil, &gqlerror.Error{
				Message: "request in progress",
				Extensions: map[string]any{
					"code": "CONFLICT",
				},
			}
		case errors.Is(err, publishsvc.ErrBundleNotFound):
			return nil, &gqlerror.Error{
				Message: "bundle not found in storage",
				Extensions: map[string]any{
					"code": "BUNDLE_NOT_FOUND",
				},
			}
		default:
			return nil, err
		}
	}

	return &generated.PublishRoomVersionPayload{
		RoomVersion: mapRoomVersion(roomVersion),
	}, nil
}

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, input generated.StartRunInput) (*generated.StartRunPayload, error) {
	user, ok := authtransport.UserFromContext(ctx)
	if !ok {
		return nil, &gqlerror.Error{
			Message: "unauthorized",
			Extensions: map[string]any{
				"code": "UNAUTHORIZED",
			},
		}
	}
	if r.CatalogRepo == nil {
		return nil, fmt.Errorf("catalog repo is nil")
	}
	if r.RunService == nil {
		return nil, fmt.Errorf("run service is nil")
	}

	room, err := r.CatalogRepo.GetBySlug(ctx, input.RoomSlug)
	if err != nil {
		return nil, err
	}
	if room == nil {
		return nil, &gqlerror.Error{
			Message: "room not found",
			Extensions: map[string]any{
				"code": "NOT_FOUND",
			},
		}
	}
	if room.ActiveRoomVersionID == nil {
		return nil, &gqlerror.Error{
			Message: "room has no active version",
			Extensions: map[string]any{
				"code": "NOT_FOUND",
			},
		}
	}

	result, err := r.RunService.StartRun(ctx, engineasvc.StartRunInput{
		ClientRequestID: input.ClientRequestID,
		UserID:          user.ID,
		RoomSlug:        input.RoomSlug,
		RoomVersionID:   *room.ActiveRoomVersionID,
		Engine:          room.Engine,
	})
	if err != nil {
		switch {
		case errors.Is(err, engineasvc.ErrIdempotencyConflict):
			return nil, &gqlerror.Error{
				Message: "idempotency conflict",
				Extensions: map[string]any{
					"code": "CONFLICT",
				},
			}
		case errors.Is(err, engineasvc.ErrRequestInProgress):
			return nil, &gqlerror.Error{
				Message: "request in progress",
				Extensions: map[string]any{
					"code": "CONFLICT",
				},
			}
		default:
			return nil, err
		}
	}

	return &generated.StartRunPayload{
		RunID:    result.RunID.String(),
		RunToken: result.RunToken,
	}, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*generated.Viewer, error) {
	user, ok := authtransport.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}

	var githubUsername *string
	if user.GitHubUsername != "" {
		u := user.GitHubUsername
		githubUsername = &u
	}

	return &generated.Viewer{
		UserID:         user.ID.String(),
		Role:           user.Role,
		GithubUsername: githubUsername,
	}, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, engine *generated.RoomEngine, difficulty *generated.RoomDifficulty, district *string) ([]*generated.Room, error) {
	if r.CatalogRepo == nil {
		return nil, fmt.Errorf("catalog repo is nil")
	}

	filter := catalogrepo.RoomFilter{
		District: district,
	}

	if engine != nil {
		e := string(*engine)
		filter.Engine = &e
	}
	if difficulty != nil {
		d := string(*difficulty)
		filter.Difficulty = &d
	}

	rooms, err := r.CatalogRepo.List(ctx, filter)
	if err != nil {
		return nil, err
	}

	result := make([]*generated.Room, 0, len(rooms))
	for _, room := range rooms {
		result = append(result, mapRoom(room))
	}
	return result, nil
}

// RoomBySlug is the resolver for the roomBySlug field.
func (r *queryResolver) RoomBySlug(ctx context.Context, slug string) (*generated.Room, error) {
	if r.CatalogRepo == nil {
		return nil, fmt.Errorf("catalog repo is nil")
	}

	room, err := r.CatalogRepo.GetBySlug(ctx, slug)
	if err != nil {
		return nil, err
	}
	if room == nil {
		return nil, nil
	}
	return mapRoom(*room), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
